name: flutter_reactive_ble_example
description: Demonstrates how to use the flutter_reactive_ble plugin.
version: 1.0.0-nullsafety.0
publish_to: 'none'

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble:
    path: ../
  provider: ^5.0.0-nullsafety.2

dev_dependencies:
  dependency_validator: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
